---

- name: Ensure build dependencies are installed
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: 'git' , state: 'installed' }
    - { name: 'gcc' , state: 'installed' }
    - { name: 'gcc-c++', state: 'installed' }
    - { name: 'make', state: 'installed' }
    - { name: 'cmake', state: 'installed' }
    - { name: 'kernel-devel', state: 'installed' }

- name: Git clone moongen
  git:
    repo: "{{ moongen_git_repo }}"
    dest: "{{ moongen_dir }}"
    update: "yes"
    clone: "yes"
    force: "yes"

- name: Replace bind-interfaces.sh file
  template:
    src: "{{ bind_interfaces_script }}"
    dest: "{{ moongen_dir }}/bind-interfaces.sh"
    force: yes
    mode: a+x

- name: Build moongen
  shell: "{{ moongen_dir }}/build.sh >> {{ build_log }}"

- name: Configure dpdk-conf.lua file
  template:
    src: "{{ dpdk_conf_lua }}"
    dest: "{{ moongen_dir }}/lua/dpdk-conf.lua"

- name: Set dpdk module to load on boot
  lineinfile:
    dest: "/etc/modules-load.d/{{ item.name }}.conf"
    regexp: "^{{ item.name }}"
    line: "{{ item.name }}"
    create: yes
  with_items:
    - { name: "{{ dpdk_module }}" }

- name: Create driverctl.sh configuration file
  template:
    src: "{{ driverctl_script }}"
    dest: "/root/driverctl.sh"

- name: Set permission to driverctl.sh
  file:
    path: "{{ item.path }}"
    mode: 0755
  with_items:
    - { path: '/root/driverctl.sh' }

- name: Set nic to bind on boot
  shell: "/root/driverctl.sh"
